apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-router" (include "cube.fullname" .) }}
  labels:
    app.kubernetes.io/component: router
    {{- include "cube.labels" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- toYaml .Values.commonLabels | nindent 4 }}
    {{- end }}
  {{- if (or .Values.commonAnnotations .Values.router.service.annotations) }}
  annotations:
    {{- if .Values.commonAnnotations }} 
    {{- toYaml .Values.commonAnnotations | nindent 4 }}
    {{- end }}
    {{- if .Values.router.service.annotations }}
    {{- toYaml .Values.router.service.annotations | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  ports:
    - name: http
      port: {{ .Values.router.httpPort }}
      targetPort: http
    - name: meta
      port: {{ .Values.router.metaPort }}
      targetPort: meta
    {{- if .Values.cubestore.metrics.port }}
    - name: metrics
      port: {{ .Values.cubestore.metrics.port }}
      targetPort: metrics
    {{- end }}
    {{- if .Values.exporter.service.port }}
    - name: http-metrics
      port: {{ .Values.exporter.service.port }}
      targetPort: http-metrics
    {{- end }}
    {{- if .Values.router.mysqlPort }}
    - name: mysql
      port: {{ .Values.router.mysqlPort }}
      targetPort: mysql
    {{- end }}
  selector:
    app.kubernetes.io/component: router
    {{- include "cube.selectorLabels" . | nindent 4 }}
