{{- if gt (.Values.workers.workersCount | int) 0 }}
apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-headless" (include "cube.fullname" .) }}
  labels:
    app.kubernetes.io/component: workers
    {{- include "cube.labels" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- toYaml .Values.commonLabels | nindent 4 }}
    {{- end }}
  {{- if (or .Values.commonAnnotations .Values.workers.service.annotations) }}
  annotations:
    {{- if .Values.commonAnnotations }} 
    {{- toYaml .Values.commonAnnotations | nindent 4 }}
    {{- end }}
    {{- if .Values.workers.service.annotations }}
    {{- toYaml .Values.workers.service.annotations | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: worker
      port: {{ .Values.workers.port }}
      targetPort: worker
  selector:
    app.kubernetes.io/component: workers
    {{- include "cube.selectorLabels" . | nindent 4 }}
{{- end }}
